#\!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."
OUT=generated/rust
rm -rf "$OUT"
mkdir -p "$OUT"
command -v thrift >/dev/null 2>&1 || { echo "error: thrift compiler not found" >&2; exit 127; }
thrift --gen rs -out "$OUT" idl/telemetry.thrift
mkdir -p "$OUT/src"
shopt -s nullglob
for f in "$OUT"/*.rs; do mv "$f" "$OUT/src/"; done
cat > "$OUT/Cargo.toml" << CARGO
[package]
name = "telemetry-thrift"
version = "0.1.0"
edition = "2021"

[dependencies]
thrift = "0.17"
CARGO
{
  echo "// Generated by Thrift"
  for f in "$OUT/src"/*.rs; do
    bn=$(basename "$f" .rs)
    echo "pub mod $bn;"
    echo "pub use $bn::*;"
  done
} > "$OUT/src/lib.rs"
