#\!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."
OUT=generated/rust
rm -rf "$OUT"
mkdir -p "$OUT"

# Ensure thrift compiler is available
if \! command -v thrift >/dev/null 2>&1; then
  echo "error: thrift compiler not found" >&2
  exit 127
fi

# Generate Rust code from Thrift
thrift --gen rs -out "$OUT" idl/telemetry.thrift

# Move all .rs into src/
mkdir -p "$OUT/src"
shopt -s nullglob
for f in "$OUT"/*.rs; do
  mv "$f" "$OUT/src/"
done

# Write Cargo.toml
cat > "$OUT/Cargo.toml" << CARGO
[package]
name = "telemetry-thrift"
version = "0.1.0"
edition = "2021"

[dependencies]
thrift = "0.17"
CARGO

# Build module list BEFORE creating lib.rs, exclude lib.rs itself
mods=()
shopt -s nullglob
for f in "$OUT/src"/*.rs; do
  bn="$(basename "$f" .rs)"
  [[ "$bn" == "lib" ]] && continue
  mods+=("$bn")
done

# Write lib.rs from the precomputed list (skip self)
{
  echo "// Generated by Thrift"
  for bn in "${mods[@]}"; do
    echo "pub mod "$bn";"
    echo "pub use "$bn"::*;"
  done
} > "$OUT/src/lib.rs"
